### ISSUE TITLE
能否支持下msgpack?

### ISSUE THREAD

**Issue by yunfan** [openLuat/Luat_4G_ASR_1802#2]
对于片上资源我不太了解具体有多少 所以希望能尽量使用msgpack这类二进制的序列化
同时又不至于使用太复杂的protobuffer

**Comment by chenxuuu** [comment]
你可以参考[https://github.com/kieselsteini/msgpack](https://github.com/kieselsteini/msgpack)用纯lua做一个就行了
需要注意的是，这个项目是lua5.3，你需要更改一些逻辑，并且需要把里面使用的string.pack换成luat的pack库写法

**Comment by yunfan** [comment]
@chenxuuu 纯的当然可以 之所以在这里提 就是希望有个c实现的 性能上好点 毕竟是嵌入式芯片

另外还有个问题是这个环境是否支持moonscript

**Comment by chenxuuu** [comment]
moonscript你可以尝试编译成lua，烧到模块里面用，具体没试过
